version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running linting checks..."
      - pylint src/
      - echo "Pylint check Passed"
      - echo "Installing Trivy......."
      - apt-get update
      - apt-get install wget apt-transport-https gnupg
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
      - echo deb https://aquasecurity.github.io/trivy-repo/deb bionic main | tee -a /etc/apt/sources.list.d/trivy.list
      - apt-get update
      - apt-get install -y trivy
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 232048837608.dkr.ecr.us-east-1.amazonaws.com
      - echo Logged in to Amazon ECR successfully

  build:
    commands:
      - echo "Scanning Dockerfile for Vulnerability and Security"
      - trivy config --severity CRITICAL Dockerfile 
      - echo Building Docker Image for Flask Application
      - docker build -t adex-ecr .
      - echo Image built successfully

  post_build:
    commands:
      - echo "Docker Container Image Scanning for Vulnerability"
      - trivy image --exit-code 1 --severity HIGH,CRITICAL adex-ecr
      - echo Tagging Flask Docker image
      - docker tag adex-ecr:latest 232048837608.dkr.ecr.us-east-1.amazonaws.com/adex-ecr:latest
      - docker push 232048837608.dkr.ecr.us-east-1.amazonaws.com/adex-ecr:latest
      - echo Flask image pushed to ECR
      - printf '[{"name":"your.task.definition.container.name","imageUri":"%s"}]' 232048837608.dkr.ecr.us-east-1.amazonaws.com/adex-ecr:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json